import test from 'node:test';
import assert from 'node:assert/strict';
import {
  assertProductAccountingAccounts,
  isAutoGeneratedTimestampSku,
} from '../services/inventory/productAccounting.js';

test('assertProductAccountingAccounts blocks sold product without income', async () => {
  await assert.rejects(
    () => assertProductAccountingAccounts('507f1f77bcf86cd799439011', {
      canBeSold: true,
      canBePurchased: false,
      productType: 'service',
      trackInventory: false,
    }),
    (err) => err?.code === 'PRODUCT_ACCOUNTS_REQUIRED',
  );
});

test('assertProductAccountingAccounts blocks sold goods without COGS', async () => {
  await assert.rejects(
    () => assertProductAccountingAccounts('507f1f77bcf86cd799439011', {
      canBeSold: true,
      productType: 'goods',
      trackInventory: true,
      incomeAccountId: '507f1f77bcf86cd799439012',
    }),
    (err) => err?.code === 'PRODUCT_ACCOUNTS_REQUIRED'
      && err?.details?.missing?.includes('expenseAccountId'),
  );
});

test('assertProductAccountingAccounts allows sold goods with income + COGS', async () => {
  await assert.doesNotReject(() => assertProductAccountingAccounts('507f1f77bcf86cd799439011', {
    canBeSold: true,
    productType: 'goods',
    incomeAccountId: '507f1f77bcf86cd799439012',
    expenseAccountId: '507f1f77bcf86cd799439013',
  }));
});

test('assertProductAccountingAccounts allows sold service with income only', async () => {
  await assert.doesNotReject(() => assertProductAccountingAccounts('507f1f77bcf86cd799439011', {
    canBeSold: true,
    productType: 'service',
    trackInventory: false,
    incomeAccountId: '507f1f77bcf86cd799439012',
  }));
});

test('assertProductAccountingAccounts allows unsold product without income', async () => {
  await assert.doesNotReject(() => assertProductAccountingAccounts('507f1f77bcf86cd799439011', {
    canBeSold: false,
    canBePurchased: false,
  }));
});

test('isAutoGeneratedTimestampSku detects invoice-created SKUs', () => {
  assert.equal(isAutoGeneratedTimestampSku('SKU-1787994744218-0-622'), true);
  assert.equal(isAutoGeneratedTimestampSku('FRT-00042'), false);
  assert.equal(isAutoGeneratedTimestampSku('GEN-00001'), false);
});
