/**
 * Maqder Built-in High Performance Bilingual Translation Engine (English <-> Arabic)
 * 
 * Zero latency, zero external API dependencies, offline-ready.
 * Covers:
 * 1. Curated bilingual dictionary for Retail, FMCG, Grocery, Restaurant, Boutique/Tailor,
 *    Bookstore, Electronics, Automotive/Workshop, HR, Accounting, POS, ZATCA, Government.
 * 2. Smart compound-phrase matcher & morphology handler (noun-adjective inversion in Arabic).
 * 3. Popular brands, Saudi company names, Saudi cities, and personal names.
 * 4. Rule-based phonetic transliteration engine for unlisted names and loanwords.
 */

// ── 1. CORE EXACT-MATCH & PHRASE DICTIONARY ──────────────────────────────────
export const DICTIONARY = {
  // --- Common Actions, UI & Statuses ---
  "save": "حفظ",
  "cancel": "إلغاء",
  "delete": "حذف",
  "edit": "تعديل",
  "update": "تحديث",
  "create": "إنشاء",
  "add": "إضافة",
  "remove": "إزالة",
  "search": "بحث",
  "filter": "تصفية",
  "sort": "ترتيب",
  "print": "طباعة",
  "download": "تحميل",
  "upload": "رفع",
  "export": "تصدير",
  "import": "استيراد",
  "preview": "معاينة",
  "submit": "إرسال",
  "confirm": "تأكيد",
  "close": "إغلاق",
  "open": "فتح",
  "back": "رجوع",
  "next": "التالي",
  "previous": "السابق",
  "select": "اختيار",
  "all": "الكل",
  "none": "لا شيء",
  "active": "نشط",
  "inactive": "غير نشط",
  "enabled": "مفعّل",
  "disabled": "معطّل",
  "pending": "قيد الانتظار",
  "approved": "معتمد",
  "rejected": "مرفوض",
  "completed": "مكتمل",
  "in progress": "قيد التنفيذ",
  "cancelled": "ملغي",
  "draft": "مسودة",
  "published": "منشور",
  "archived": "مؤرشف",
  "paid": "مدفوع",
  "unpaid": "غير مدفوع",
  "partially paid": "مدفوع جزئياً",
  "overdue": "متأخر",
  "refunded": "مسترد",
  "returned": "مرتجع",
  "success": "ناجح",
  "failed": "فاشل",
  "error": "خطأ",
  "warning": "تحذير",
  "info": "معلومات",
  "loading": "جاري التحميل",
  "processing": "جاري المعالجة",
  "syncing": "جاري المزامنة",
  "online": "متصل",
  "offline": "غير متصل",
  "available": "متوفر",
  "out of stock": "نفد من المخزون",
  "in stock": "متوفر بالمخزون",
  "low stock": "مخزون منخفض",

  // --- Invoicing, POS, Accounting & Finance ---
  "invoice": "فاتورة",
  "invoices": "فواتير",
  "tax invoice": "فاتورة ضريبية",
  "simplified tax invoice": "فاتورة ضريبية مبسطة",
  "simplified invoice": "فاتورة مبسطة",
  "standard invoice": "فاتورة قياسية",
  "proforma invoice": "فاتورة أولية",
  "commercial invoice": "فاتورة تجارية",
  "credit note": "إشعار دائن",
  "debit note": "إشعار مدين",
  "receipt": "إيصال",
  "payment receipt": "سند قبض",
  "payment voucher": "سند صرف",
  "receipt voucher": "سند استلام",
  "journal voucher": "سند قيد",
  "quotation": "عرض سعر",
  "quotations": "عروض أسعار",
  "purchase order": "أمر شراء",
  "sales order": "أمر بيع",
  "delivery note": "إشعار تسليم",
  "subtotal": "المجموع الفرعي",
  "total": "الإجمالي",
  "grand total": "الإجمالي الكلي",
  "total amount": "المبلغ الإجمالي",
  "net amount": "المبلغ الصافي",
  "paid amount": "المبلغ المدفوع",
  "remaining amount": "المبلغ المتبقي",
  "balance due": "الرصيد المستحق",
  "balance": "الرصيد",
  "change": "المتبقي / الفكة",
  "tax": "الضريبة",
  "taxes": "الضرائب",
  "vat": "ضريبة القيمة المضافة",
  "vat amount": "مبلغ ضريبة القيمة المضافة",
  "vat rate": "نسبة الضريبة",
  "15% vat": "ضريبة القيمة المضافة 15%",
  "zero vat": "ضريبة صفرية",
  "tax exempt": "معفى من الضريبة",
  "discount": "خصم",
  "special discount": "خصم خاص",
  "percentage discount": "خصم نسبة مئوية",
  "fixed discount": "خصم بمبلغ ثابت",
  "cash": "نقداً",
  "card": "بطاقة",
  "credit card": "بطاقة ائتمان",
  "mada": "مدى",
  "apple pay": "أبل باي",
  "visa": "فيزا",
  "mastercard": "ماستركارد",
  "bank transfer": "تحويل بنكي",
  "cheque": "شيك",
  "on account": "على الحساب / آجل",
  "split payment": "دفع مجزأ",
  "deposit": "عربون / دفعة مقدمة",
  "refund": "استرداد",
  "customer": "العميل",
  "customer name": "اسم العميل",
  "supplier": "المورد",
  "supplier name": "اسم المورد",
  "vendor": "المورد / البائع",
  "buyer": "المشتري",
  "seller": "البائع",
  "cashier": "الكاشير",
  "salesman": "مندوب المبيعات",
  "salesperson": "البائع",
  "description": "الوصف",
  "item description": "وصف الصنف",
  "item": "الصنف",
  "items": "الأصناف",
  "quantity": "الكمية",
  "qty": "الكمية",
  "unit price": "سعر الوحدة",
  "price": "السعر",
  "cost price": "سعر التكلفة",
  "retail price": "سعر التجزئة",
  "wholesale price": "سعر الجملة",
  "total price": "السعر الإجمالي",
  "barcode": "الباركود",
  "sku": "رمز الصنف",
  "serial number": "الرقم التسلسلي",
  "batch number": "رقم التشغيلة",
  "lot number": "رقم الشحنة",
  "expiry date": "تاريخ الانتهاء",
  "production date": "تاريخ الإنتاج",
  "issue date": "تاريخ الإصدار",
  "due date": "تاريخ الاستحقاق",
  "supply date": "تاريخ التوريد",
  "invoice date": "تاريخ الفاتورة",
  "invoice number": "رقم الفاتورة",
  "reference number": "الرقم المرجعي",
  "terms and conditions": "الشروط والأحكام",
  "notes": "ملاحظات",
  "signature": "التوقيع",
  "authorized signature": "التوقيع المعتمد",
  "official stamp": "الختم الرسمي",

  // --- ZATCA & Saudi Government Compliance ---
  "zatca": "هيئة الزكاة والضريبة والجمارك",
  "zatca phase 2": "المرحلة الثانية للربط والتكامل (فاتورة)",
  "cryptographic stamp": "الختم الرقمي المشفر",
  "qr code": "رمز الاستجابة السريعة QR",
  "invoice hash": "هاش الفاتورة",
  "previous invoice hash": "هاش الفاتورة السابقة",
  "commercial registration": "السجل التجاري",
  "cr number": "رقم السجل التجاري",
  "vat registration number": "رقم التسجيل الضريبي",
  "national address": "العنوان الوطني",
  "building number": "رقم المبنى",
  "street name": "اسم الشارع",
  "district": "الحي",
  "city": "المدينة",
  "postal code": "الرمز البريدي",
  "additional number": "الرقم الإضافي",
  "country": "الدولة",
  "saudi arabia": "المملكة العربية السعودية",
  "kingdom of saudi arabia": "المملكة العربية السعودية",
  "gosi": "التأمينات الاجتماعية",
  "muqeem": "مقيم",
  "qiwa": "قوى",
  "mudad": "مدد",
  "wps": "حماية الأجور",
  "national id": "الهوية الوطنية",
  "iqama": "الإقامة",
  "iqama number": "رقم الإقامة",
  "passport": "جواز السفر",
  "driving license": "رخصة القيادة",

  // --- Units of Measurement ---
  "piece": "حبة",
  "pieces": "حبات",
  "pcs": "حبة",
  "box": "كرتون",
  "boxes": "كراتين",
  "pack": "باكيت / باكت",
  "packet": "باكيت",
  "packs": "باكيتات",
  "carton": "كرتون",
  "cartons": "كراتين",
  "bag": "كيس",
  "bags": "أكياس",
  "bottle": "قارورة / زجاجة",
  "bottles": "قوارير",
  "can": "علبة",
  "cans": "علب",
  "jar": "مرطبان",
  "dozen": "درزن",
  "dozens": "دراتن",
  "pair": "زوج",
  "pairs": "أزواج",
  "set": "طقم",
  "sets": "أطقم",
  "bundle": "حزمة",
  "roll": "لفة / رول",
  "rolls": "لفات",
  "kg": "كيلوجرام",
  "kilogram": "كيلوجرام",
  "kilograms": "كيلوجرام",
  "g": "جرام",
  "gram": "جرام",
  "grams": "جرام",
  "mg": "مليجرام",
  "ton": "طن",
  "l": "لتر",
  "liter": "لتر",
  "liters": "لتر",
  "litre": "لتر",
  "litres": "لتر",
  "ml": "ملليلتر",
  "milliliter": "ملليلتر",
  "m": "متر",
  "meter": "متر",
  "meters": "أمتار",
  "metre": "متر",
  "cm": "سنتيمتر",
  "centimeter": "سنتيمتر",
  "mm": "مليمتر",
  "millimeter": "مليمتر",
  "inch": "بوصة / إنش",
  "inches": "بوصات",
  "foot": "قدم",
  "feet": "أقدام",
  "yard": "ياردة",
  "sqm": "متر مربع",
  "square meter": "متر مربع",
  "hour": "ساعة",
  "hours": "ساعات",
  "day": "يوم",
  "days": "أيام",
  "week": "أسبوع",
  "weeks": "أسابيع",
  "month": "شهر",
  "months": "أشهر",
  "year": "سنة",
  "years": "سنوات",
  "shift": "وردية",
  "service": "خدمة",
  "session": "جلسة",
  "trip": "رحلة",
  "visit": "زيارة",
  "unit": "وحدة",
  "units": "وحدات",

  // --- Bakery, Grocery, Dairy & Supermarket (Bakala) ---
  "milk": "حليب",
  "fresh milk": "حليب طازج",
  "full fat milk": "حليب كامل الدسم",
  "low fat milk": "حليب قليل الدسم",
  "skimmed milk": "حليب منزوع الدسم",
  "powder milk": "حليب بودرة",
  "evaporated milk": "حليب مبخر",
  "condensed milk": "حليب مكثف محلى",
  "yogurt": "زبادي",
  "fresh yogurt": "زبادي طازج",
  "laban": "لبن",
  "fresh laban": "لبن طازج",
  "ayran": "لبن عيران",
  "butter": "زبدة",
  "salted butter": "زبدة مملحة",
  "unsalted butter": "زبدة غير مملحة",
  "ghee": "سمن",
  "cream": "قشطة",
  "whipping cream": "كريمة خفق",
  "cooking cream": "كريمة طبخ",
  "cheese": "جبنة",
  "cheddar cheese": "جبنة شيدر",
  "mozzarella cheese": "جبنة موزاريلا",
  "feta cheese": "جبنة فيتا",
  "cream cheese": "جبنة كريمية",
  "slice cheese": "جبنة شرائح",
  "halloumi cheese": "جبنة حلوم",
  "parmesan cheese": "جبنة بارميزان",
  "eggs": "بيض",
  "egg": "بيضة",
  "fresh eggs": "بيض طازج",
  "large eggs": "بيض كبير",
  "medium eggs": "بيض وسط",
  "bread": "خبز",
  "white bread": "خبز أبيض",
  "brown bread": "خبز بر",
  "whole wheat bread": "خبز بر قمح كامل",
  "pita bread": "خبز عربي / بيتا",
  "samoli bread": "خبز صامولي",
  "toast bread": "خبز توست",
  "burger bun": "خبز برجر",
  "tortilla": "خبز تورتیلا",
  "croissant": "كرواسون",
  "cheese croissant": "كرواسون جبن",
  "chocolate croissant": "كرواسون شوكولاتة",
  "flour": "دقيق / طحين",
  "white flour": "دقيق أبيض",
  "wheat flour": "دقيق بر / قمح",
  "sugar": "سكر",
  "white sugar": "سكر أبيض",
  "brown sugar": "سكر بني",
  "icing sugar": "سكر بودرة",
  "salt": "ملح",
  "table salt": "ملح طعام",
  "sea salt": "ملح بحري",
  "rice": "أرز",
  "basmati rice": "أرز بسمتي",
  "egyptian rice": "أرز مصري",
  "white rice": "أرز أبيض",
  "brown rice": "أرز بني",
  "cooking oil": "زيت طهي",
  "vegetable oil": "زيت نباتي",
  "corn oil": "زيت ذرة",
  "sunflower oil": "زيت دوار الشمس",
  "olive oil": "زيت زيتون",
  "extra virgin olive oil": "زيت زيتون بكر ممتاز",
  "sesame oil": "زيت سمسم",
  "pasta": "مكرونة",
  "macaroni": "معكرونة",
  "spaghetti": "سباغيتي",
  "penne pasta": "مكرونة بيني",
  "noodles": "نودلز / إندومي",
  "instant noodles": "شعرية سريعة التحضير / إندومي",
  "tomato paste": "معجون طماطم",
  "tomato sauce": "صلصة طماطم",
  "ketchup": "كاتشب",
  "mayonnaise": "مايونيز",
  "mustard": "خردل",
  "hot sauce": "شطة / صلصة حارة",
  "vinegar": "خل",
  "white vinegar": "خل أبيض",
  "apple cider vinegar": "خل تفاح",
  "tuna": "تونة",
  "canned tuna": "تونة معلبة",
  "sardines": "سردين",
  "canned fava beans": "فول مدمس",
  "fava beans": "فول مدمس",
  "chickpeas": "حمص حب",
  "canned chickpeas": "حمص معلب",
  "lentils": "عدس",
  "red lentils": "عدس أحمر",
  "brown lentils": "عدس بني / أخضر",
  "green peas": "بازلاء خضراء",
  "sweet corn": "ذرة حلوة",
  "meat": "لحم",
  "beef": "لحم بقري",
  "lamb": "لحم غنم / خروف",
  "mutton": "لحم ضأن",
  "veal": "لحم عجل",
  "camel meat": "لحم حاشي / جمل",
  "chicken": "دجاج",
  "fresh chicken": "دجاج طازج",
  "frozen chicken": "دجاج مجمد",
  "chicken breast": "صدور دجاج",
  "chicken thighs": "أفخاذ دجاج",
  "chicken wings": "أجنحة دجاج",
  "whole chicken": "دجاجة كاملة",
  "minced meat": "لحم مفروم",
  "minced beef": "لحم بقري مفروم",
  "minced chicken": "دجاج مفروم",
  "fish": "سمك",
  "salmon": "سلمون",
  "shrimp": "روبيان / جمبري",
  "prawns": "روبيان كبير",
  "water": "مياه / ماء",
  "mineral water": "مياه معدنية",
  "drinking water": "مياه شرب",
  "sparkling water": "مياه فوارة",
  "juice": "عصير",
  "fresh juice": "عصير طازج",
  "orange juice": "عصير برتقال",
  "apple juice": "عصير تفاح",
  "mango juice": "عصير مانجو",
  "guava juice": "عصير جوافة",
  "mixed fruit juice": "عصير فواكه مشكلة",
  "lemon juice": "عصير ليمون",
  "lemonade": "عصير ليمونادة",
  "grape juice": "عصير عنب",
  "pineapple juice": "عصير أناناس",
  "pomegranate juice": "عصير رمان",
  "tea": "شاي",
  "black tea": "شاي أسود",
  "green tea": "شاي أخضر",
  "karak tea": "شاي كرك",
  "mint tea": "شاي بالنعناع",
  "tea bags": "أكياس شاي",
  "loose tea": "شاي فرط",
  "coffee": "قهوة",
  "arabic coffee": "قهوة عربية",
  "turkish coffee": "قهوة تركية",
  "instant coffee": "قهوة سريعة التحضير",
  "ground coffee": "قهوة مطحونة",
  "coffee beans": "حبوب قهوة",
  "espresso": "إسبريسو",
  "soft drink": "مشروب غازي",
  "soda": "صودا",
  "cola": "كولا",
  "energy drink": "مشروب طاقة",
  "malt beverage": "مشروب شعير",
  "biscuits": "بسكويت",
  "biscuit": "بسكويت",
  "cookies": "كوكيز",
  "wafer": "ويفر",
  "chocolate": "شوكولاتة",
  "dark chocolate": "شوكولاتة داكنة",
  "milk chocolate": "شوكولاتة بالحليب",
  "candy": "حلوى / حلويات",
  "gum": "علكة",
  "chewing gum": "علكة",
  "chips": "شيبس / رقائق بطاطس",
  "potato chips": "شيبس بطاطس",
  "corn chips": "شيبس ذرة",
  "popcorn": "فشار",
  "nuts": "مكسرات",
  "mixed nuts": "مكسرات مشكلة",
  "almonds": "لوز",
  "pistachio": "فستق",
  "cashew": "كاجو",
  "walnuts": "عين الجمل / جوز",
  "peanuts": "فول سوداني",
  "sunflower seeds": "حب دوار الشمس / فصفص",
  "dates": "تمر",
  "ajwa dates": "تمر عجوة",
  "sukkari dates": "تمر سكري",
  "khalas dates": "تمر خلاص",
  "sagae dates": "تمر صقعي",
  "safawi dates": "تمر صفاوي",
  "medjool dates": "تمر مجدول",
  "apple": "تفاح",
  "red apple": "تفاح أحمر",
  "green apple": "تفاح أخضر",
  "yellow apple": "تفاح أصفر",
  "banana": "موز",
  "orange": "برتقال",
  "mandarin": "يوسفي / كلمنتينا",
  "lemon": "ليمون",
  "lime": "ليمون أخضر",
  "watermelon": "بطيخ",
  "sweet melon": "شمام",
  "grapes": "عنب",
  "red grapes": "عنب أحمر",
  "green grapes": "عنب أخضر",
  "strawberry": "فراولة",
  "mango": "مانجو",
  "pineapple": "أناناس",
  "peach": "خوخ",
  "plum": "بخارى / برقوق",
  "apricot": "مشمش",
  "pomegranate": "رمان",
  "kiwi": "كيوي",
  "avocado": "أفوكادو",
  "tomato": "طماطم",
  "potato": "بطاطس",
  "onion": "بصل",
  "red onion": "بصل أحمر",
  "white onion": "بصل أبيض",
  "garlic": "ثوم",
  "cucumber": "خيار",
  "lettuce": "خس",
  "iceberg lettuce": "خس أمريكي / كابوتشا",
  "carrot": "جزر",
  "bell pepper": "فلفل رومي / بارد",
  "green pepper": "فلفل أخضر",
  "red pepper": "فلفل أحمر",
  "yellow pepper": "فلفل أصفر",
  "chili pepper": "فلفل حار",
  "eggplant": "باذنجان",
  "zucchini": "كوسة",
  "cabbage": "ملفوف / كرنب",
  "cauliflower": "قرنبيط / زهرة",
  "broccoli": "بروكلي",
  "spinach": "سبانخ",
  "mint": "نعناع",
  "parsley": "بقدونس",
  "coriander": "كزبرة",
  "dill": "شبت",
  "ginger": "زنجبيل",
  "mushrooms": "فطر / مشروم",
  "soap": "صابون",
  "hand soap": "صابون لليدين",
  "bar soap": "صابون لوح",
  "liquid soap": "صابون سائل",
  "shampoo": "شامبو",
  "conditioner": "بلسم",
  "hair conditioner": "بلسم للشعر",
  "body wash": "غسول للجسم / شاور جل",
  "shower gel": "جل استحمام",
  "toothpaste": "معجون أسنان",
  "toothbrush": "فرشاة أسنان",
  "mouthwash": "غسول فم",
  "face wash": "غسول للوجه",
  "body lotion": "لوشن للجسم",
  "hand cream": "كريم لليدين",
  "deodorant": "مزيل عرق",
  "perfume": "عطر",
  "body spray": "بخاخ للجسم",
  "tissues": "مناديل",
  "facial tissues": "مناديل وجه",
  "wet wipes": "مناديل مبللة",
  "toilet paper": "ورق تواليت / حمام",
  "kitchen towels": "مناديل مطبخ",
  "paper towels": "ورق تنشيف",
  "laundry detergent": "مسحوق غسيل ملابس",
  "detergent powder": "مسحوق غسيل",
  "liquid detergent": "منظف سائل",
  "dishwashing liquid": "سائل غسيل الصحون",
  "dish soap": "صابون صحون",
  "bleach": "مبيض / كلور",
  "fabric softener": "منعم أقمشة",
  "disinfectant": "مطهر / معقم",
  "floor cleaner": "منظف أرضيات",
  "glass cleaner": "منظف زجاج",
  "trash bags": "أكياس نفايات",
  "garbage bags": "أكياس قمامة",
  "aluminum foil": "قصدير / ورق ألمنيوم",
  "cling film": "نايلون تغليف أطعمة",
  "baking paper": "ورق زبدة / خبز",
  "plastic cups": "أكواب بلاستيك",
  "paper cups": "أكواب ورقية",
  "plastic plates": "صحون بلاستيك",
  "sponges": "إسفنج تنظيف",
  "batteries": "بطاريات",
  "lighter": "ولاعة",
  "matches": "كبريت",
  "charcoal": "فحم",

  // --- Restaurant, Fast Food, Cafe & Desserts ---
  "burger": "برجر",
  "beef burger": "برجر لحم",
  "chicken burger": "برجر دجاج",
  "double beef burger": "برجر لحم دبل",
  "double chicken burger": "برجر دجاج دبل",
  "cheese burger": "تشيز برجر",
  "crispy chicken burger": "برجر دجاج مقرمش",
  "grilled chicken burger": "برجر دجاج مشوي",
  "zinger burger": "برجر زنجر",
  "shawarma": "شاورما",
  "chicken shawarma": "شاورما دجاج",
  "meat shawarma": "شاورما لحم",
  "arabic shawarma": "شاورما عربي",
  "shawarma plate": "صحن شاورما",
  "shawarma wrap": "ساندويتش شاورما",
  "pizza": "بيتزا",
  "margarita pizza": "بيتزا مارغريتا",
  "margherita pizza": "بيتزا مارغريتا",
  "pepperoni pizza": "بيتزا بيبروني",
  "chicken pizza": "بيتزا دجاج",
  "bbq chicken pizza": "بيتزا دجاج باربكيو",
  "vegetable pizza": "بيتزا خضار",
  "four cheese pizza": "بيتزا أربعة أجبان",
  "seafood pizza": "بيتزا مأكولات بحرية",
  "sandwich": "ساندويتش",
  "club sandwich": "كلوب ساندويتش",
  "falafel": "فلافل",
  "falafel sandwich": "ساندويتش فلافل",
  "falafel plate": "صحن فلافل",
  "broast": "بروستد",
  "fried chicken": "دجاج مقلي",
  "spicy broast": "بروستد حار",
  "normal broast": "بروستد عادي",
  "grilled chicken": "دجاج مشوي",
  "half grilled chicken": "نصف دجاجة مشوية",
  "whole grilled chicken": "دجاجة كاملة مشوية",
  "charcoal chicken": "دجاج على الفحم",
  "kabsa": "كبسة",
  "chicken kabsa": "كبسة دجاج",
  "meat kabsa": "كبسة لحم",
  "mandi": "مندي",
  "chicken mandi": "مندي دجاج",
  "meat mandi": "مندي لحم",
  "bukhari": "بخاري",
  "chicken bukhari": "بخاري دجاج",
  "meat bukhari": "بخاري لحم",
  "madghoot": "مضغوط",
  "chicken madghoot": "مضغوط دجاج",
  "meat madghoot": "مضغوط لحم",
  "zurbian": "زربيان",
  "biryani": "برياني",
  "chicken biryani": "برياني دجاج",
  "meat biryani": "برياني لحم",
  "kebab": "كباب",
  "meat kebab": "كباب لحم",
  "chicken kebab": "كباب دجاج",
  "shish tawook": "شيش طاووق",
  "mixed grill": "مشاوي مشكلة",
  "french fries": "بطاطس مقلية",
  "curly fries": "بطاطس كيرلي",
  "potato wedges": "ودجز بطاطس",
  "onion rings": "حلقات بصل",
  "cheese sticks": "أصابع جبنة موزاريلا",
  "chicken nuggets": "ناجتس دجاج",
  "chicken strips": "ستربس دجاج",
  "hummus": "حمص",
  "mutabbal": "متبل",
  "baba ghanoush": "بابا غنوج",
  "tabbouleh": "تبولة",
  "fattoush": "فتوش",
  "caesar salad": "سلطة سيزر",
  "chicken caesar salad": "سلطة سيزر بالدجاج",
  "green salad": "سلطة خضراء",
  "greek salad": "سلطة يونانية",
  "lentil soup": "شوربة عدس",
  "chicken soup": "شوربة دجاج",
  "mushroom soup": "شوربة فطر",
  "garlic sauce": "صلصة ثوم / ثومية",
  "tahini sauce": "طحينة",
  "bbq sauce": "صلصة باربكيو",
  "dynamite sauce": "صلصة ديناميت",
  "ranch sauce": "صلصة رانش",
  "latte": "لاتيه",
  "spanish latte": "سبانش لاتيه",
  "iced spanish latte": "آيس سبانش لاتيه",
  "cappuccino": "كابوتشينو",
  "americano": "أمريكانو",
  "flat white": "فلات وايت",
  "cortado": "كورتادو",
  "mocha": "موكا",
  "iced mocha": "آيس موكا",
  "hot chocolate": "شوكولاتة ساخنة",
  "iced coffee": "قهوة مثلجة",
  "iced latte": "آيس لاتيه",
  "iced americano": "آيس أمريكانو",
  "frappuccino": "فرابتشينو",
  "smoothie": "سموذي",
  "strawberry smoothie": "سموذي فراولة",
  "mango smoothie": "سموذي مانجو",
  "milkshake": "ميلك شيك",
  "vanilla milkshake": "ميلك شيك فانيليا",
  "chocolate milkshake": "ميلك شيك شوكولاتة",
  "oreo milkshake": "ميلك شيك أوريو",
  "mojito": "موهيتو",
  "classic mojito": "موهيتو كلاسيك",
  "strawberry mojito": "موهيتو فراولة",
  "passion fruit mojito": "موهيتو باشن فروت",
  "blue ocean mojito": "موهيتو بلو أوشن",
  "lemon mint": "ليمون بالنعناع",
  "kunafa": "كنافة",
  "cheese kunafa": "كنافة بالجبن",
  "cream kunafa": "كنافة بالقشطة",
  "baklava": "بقلاوة",
  "umm ali": "أم علي",
  "basbousa": "بسبوسة",
  "cheesecake": "تشيز كيك",
  "san sebastian cheesecake": "سان سيباستيان تشيز كيك",
  "chocolate cake": "كيك شوكولاتة",
  "brownies": "براونيز",
  "pancake": "بان كيك",
  "waffle": "وافل",
  "crepe": "كريب",
  "donut": "دونات",
  "muffin": "مافن",
  "cupcake": "كب كيك",
  "combo meal": "وجبة كومبو",
  "kids meal": "وجبة أطفال",
  "family meal": "وجبة عائلية",
  "meal": "وجبة",
  "dine in": "محلي",
  "takeaway": "سفري",
  "delivery": "توصيل",
  "drive thru": "طلب سيارات",
  "table": "طاولة",

  // --- Tailoring (Khayyat), Boutique & Garments ---
  "thobe": "ثوب",
  "saudi thobe": "ثوب سعودي",
  "emirati thobe": "ثوب إماراتي",
  "kuwaiti thobe": "ثوب كويتي",
  "qatari thobe": "ثوب قطري",
  "omani thobe": "ثوب عماني",
  "moroccan thobe": "ثوب مغربي",
  "abaya": "عباية",
  "plain abaya": "عباية سادة",
  "embroidered abaya": "عباية مطرزة",
  "formal abaya": "عباية رسمية",
  "casual abaya": "عباية يومية",
  "kaftan": "قفطان",
  "jalabiya": "جلابية",
  "dress": "فستان",
  "evening dress": "فستان سهرة",
  "wedding dress": "فستان زفاف / عروس",
  "casual dress": "فستان يومي",
  "shirt": "قميص",
  "formal shirt": "قميص رسمي",
  "casual shirt": "قميص كاجوال",
  "t-shirt": "تيشيرت",
  "polo shirt": "قميص بولو",
  "pants": "بنطلون",
  "trousers": "بنطلون",
  "jeans": "جينز",
  "formal pants": "بنطلون رسمي",
  "suit": "بدلة",
  "tuxedo": "بدلة رسمية توكسيدو",
  "blazer": "بليزر",
  "jacket": "جاكيت / سترة",
  "coat": "معطف",
  "vest": "صديري / سديري",
  "waistcoat": "سديري",
  "bisht": "بشت / مشلح",
  "royal bisht": "بشت ملكي",
  "shemagh": "شماغ",
  "red shemagh": "شماغ أحمر",
  "ghutra": "غترة",
  "white ghutra": "غترة بيضاء",
  "egal": "عقال",
  "igal": "عقال",
  "cap": "طاقية",
  "taqiyah": "طاقية",
  "underwear": "ملابس داخلية",
  "fabric": "قماش",
  "fabrics": "أقمشة",
  "japanese fabric": "قماش ياباني",
  "korean fabric": "قماش كوري",
  "english fabric": "قماش إنجليزي",
  "italian fabric": "قماش إيطالي",
  "cotton": "قطن",
  "pure cotton": "قطن خالص",
  "100% cotton": "قطن 100%",
  "silk": "حرير",
  "pure silk": "حرير طبيعي",
  "synthetic silk": "حرير صناعي",
  "wool": "صوف",
  "pure wool": "صوف خالص",
  "linen": "كتان",
  "polyester": "بوليستر",
  "chiffon": "شيفون",
  "georgette": "جورجيت",
  "crepe fabric": "قماش كريب",
  "velvet": "مخمل",
  "satin": "ساتان / ستان",
  "lace": "دانتيل",
  "denim": "دنيم / جينز",
  "brocade": "بروكار",
  "jacquard": "جاكار",
  "stitching": "خياطة / تفصيل",
  "tailoring": "تفصيل وخياطة",
  "custom tailoring": "تفصيل حسب الطلب",
  "urgent tailoring": "تفصيل مستعجل",
  "normal tailoring": "تفصيل عادي",
  "alteration": "تعديل / تصليح",
  "length alteration": "تقصير / تظبيط الطول",
  "waist alteration": "تضييق / توسيع الخصر",
  "sleeve alteration": "تعديل الأكمام",
  "collar": "ياقة / قبة",
  "plain collar": "ياقة سادة",
  "mandarin collar": "ياقة قلاب / صينية",
  "high collar": "ياقة مرتفعة",
  "round collar": "ياقة دائرية",
  "cuff": "كبك / أساور الكم",
  "french cuff": "كبك فرنسي",
  "regular cuff": "أساور عادية",
  "double cuff": "أساور مزدوجة",
  "pocket": "جيب",
  "chest pocket": "جيب صدر",
  "side pocket": "جيب جانبي",
  "hidden pocket": "جيب مخفي",
  "mobile pocket": "جيب جوال",
  "wallet pocket": "جيب محفظة",
  "button": "زر / زرار",
  "buttons": "أزرار",
  "shell buttons": "أزرار صدف",
  "plastic buttons": "أزرار بلاستيك",
  "metal buttons": "أزرار معدنية",
  "zipper": "سحاب",
  "hidden zipper": "سحاب مخفي",
  "embroidery": "تطريز",
  "computer embroidery": "تطريز كمبيوتر",
  "hand embroidery": "تطريز يدوي",
  "gold thread": "خيط ذهبي",
  "silver thread": "خيط فضي",
  "measurements": "المقاسات",
  "length": "الطول",
  "shoulder": "الكتف",
  "shoulder width": "عرض الكتف",
  "chest": "الصدر",
  "waist": "الخصر",
  "hips": "الأرداف / الورك",
  "sleeve": "الكم",
  "sleeve length": "طول الكم",
  "armhole": "حفرة الإبط / الجيرو",
  "neck": "الرقبة",
  "wrist": "المعصم / الكبك",
  "bottom width": "عرض الأسفل / الذيل",
  "expansion": "التوسيع",
  "fitting": "بروفة قياس",

  // --- Bookstore & Stationery ---
  "book": "كتاب",
  "books": "كتب",
  "novel": "رواية",
  "notebook": "دفتر",
  "spiral notebook": "دفتر سلك",
  "hardcover notebook": "دفتر غلاف مقوى",
  "grid notebook": "دفتر مربعات / رسم بياني",
  "lined notebook": "دفتر مسطر",
  "pen": "قلم",
  "pens": "أقلام",
  "ballpoint pen": "قلم جاف",
  "gel pen": "قلم جل",
  "ink pen": "قلم حبر",
  "fountain pen": "قلم حبر سائل",
  "pencil": "قلم رصاص",
  "mechanical pencil": "قلم رصاص ميكانيكي / سنون",
  "colored pencils": "ألوان خشبية",
  "crayons": "ألوان شمعية",
  "watercolors": "ألوان مائية",
  "marker": "قلم ماركر",
  "permanent marker": "ماركر دائم",
  "whiteboard marker": "قلم سبورة بيضاء",
  "highlighter": "قلم تظليل / هايلايتر",
  "eraser": "ممحاة / مساحة",
  "sharpener": "مبراة",
  "ruler": "مسطرة",
  "compass": "فرجار",
  "protractor": "منقلة",
  "geometry set": "طقم أدوات هندسية",
  "scissors": "مقص",
  "glue": "صمغ / غراء",
  "glue stick": "صمغ أصبع",
  "liquid glue": "غراء سائل",
  "tape": "شريط لاصق",
  "double sided tape": "شريط لاصق بوجهين",
  "masking tape": "شريط لاصق ورقي",
  "stapler": "دباسة",
  "staples": "دبابيس دباسة",
  "hole punch": "خرامة ورق",
  "paper clips": "مشابك ورق",
  "binder": "ملف / بايندر",
  "folder": "ملف حفظ أوراق",
  "clear folder": "ملف شفاف",
  "file box": "صندوق حفظ ملفات",
  "sticky notes": "ملاحظات لاصقة / ستيكي نوتس",
  "index cards": "بطاقات فهرسة",
  "paper": "ورق",
  "a4 paper": "ورق A4",
  "a3 paper": "ورق A3",
  "copy paper": "ورق تصوير",
  "photo paper": "ورق صور",
  "cardboard": "ورق مقوى / كرتون",
  "colored paper": "ورق ملون",
  "envelope": "ظرف",
  "envelopes": "أظرف",
  "school bag": "حقيبة مدرسية",
  "backpack": "حقيبة ظهر",
  "pencil case": "مقلمة",
  "calculator": "آلة حاسبة",
  "scientific calculator": "آلة حاسبة علمية",
  "desk organizer": "منظم مكتب",
  "whiteboard": "سبورة بيضاء",
  "cork board": "لوحة فلين",

  // --- Electronics, IT, Mobile & Appliances ---
  "mobile phone": "هاتف جوال",
  "smartphone": "هاتف ذكي",
  "tablet": "جهاز لوحي / تابلت",
  "laptop": "كمبيوتر محمول / لابتوب",
  "desktop pc": "كمبيوتر مكتبي",
  "monitor": "شاشة عرض",
  "screen protector": "استكر حماية شاشة",
  "privacy screen protector": "استكر حماية خصوصية",
  "case": "كفر / غطاء حماية",
  "cover": "كفر حماية",
  "leather case": "كفر جلد",
  "silicone case": "كفر سيليكون",
  "charger": "شاحن",
  "fast charger": "شاحن سريع",
  "wireless charger": "شاحن لاسلكي",
  "car charger": "شاحن سيارة",
  "charging cable": "كيبل شحن",
  "usb cable": "كيبل USB",
  "type-c cable": "كيبل تايب سي",
  "usb-c cable": "كيبل تايب سي",
  "lightning cable": "كيبل لايتنينج",
  "micro-usb cable": "كيبل مايكرو",
  "power bank": "بنك طاقة / باور بانك",
  "adapter": "محول / فيش شاحن",
  "headphone": "سماعة رأس",
  "headphones": "سماعات رأس",
  "earphones": "سماعات أذن",
  "wireless earbuds": "سماعات أذن لاسلكية",
  "bluetooth speaker": "سماعة بلوتوث",
  "smartwatch": "ساعة ذكية",
  "flash drive": "فلاش ميموري",
  "memory card": "بطاقة ذاكرة",
  "external hard drive": "قرص صلب خارجي",
  "mouse": "فأرة / ماوس",
  "wireless mouse": "ماوس لاسلكي",
  "keyboard": "لوحة مفاتيح / كيبورد",
  "wireless keyboard": "لوحة مفاتيح لاسلكية",
  "mechanical keyboard": "كيبورد ميكانيكي",
  "router": "راوتر / موجه شبكة",
  "sim card": "شريحة اتصال",
  "esim": "شريحة إلكترونية",
  "data sim": "شريحة بيانات",
  "battery": "بطارية",
  "camera": "كاميرا",
  "tripod": "حامل ثلاثي / ترايبود",
  "ring light": "إضاءة دائرية / رينق لايت",

  // --- Automotive, Workshop & Car Rental ---
  "car": "سيارة",
  "sedan": "سيدان",
  "suv": "دفع رباعي / جيب",
  "hatchback": "هاتشباك",
  "luxury car": "سيارة فارهة",
  "economy car": "سيارة اقتصادية",
  "engine": "محرك / ماكينة",
  "engine oil": "زيت محرك",
  "synthetic oil": "زيت تخليقي",
  "oil filter": "فلتر زيت / سيفون",
  "air filter": "فلتر هواء",
  "ac filter": "فلتر مكيف",
  "fuel filter": "فلتر بنزين",
  "brake pads": "فحمات فرامل / أقمشة",
  "front brake pads": "فحمات أمامية",
  "rear brake pads": "فحمات خلفية",
  "brake disc": "هوبات / ديسك فرامل",
  "brake fluid": "زيت فرامل",
  "spark plugs": "بواجي / شمعات احتراق",
  "car battery": "بطارية سيارة",
  "tire": "إطار / كفر",
  "tires": "إطارات / كفرات",
  "wheel": "جنط",
  "wheels": "جنوط",
  "wheel alignment": "ميزان أذرعة",
  "wheel balancing": "ترصيص إطارات",
  "tire repair": "رقعة كفر / تصليح بنشر",
  "radiator": "رديتر",
  "coolant": "ماء رديتر / سائل تبريد",
  "transmission fluid": "زيت جير / قير",
  "windshield wiper": "مساحات زجاج",
  "headlight": "شمعة أمامية / نور أمامي",
  "taillight": "إسطب خلفي",
  "car wash": "غسيل سيارة",
  "interior cleaning": "تنظيف داخلي",
  "car polishing": "تلميع سيارة",
  "window tinting": "تظليل زجاج",
  "maintenance service": "صيانة دورية",
  "periodic inspection": "فحص دوري",
  "computer diagnostic": "فحص كمبيوتر",
  "ac repair": "تصليح مكيف",
  "ac gas refill": "تعبئة فريون",
  "labor cost": "أجور يد / مصنعية",
  "towing": "سطحة / سحب سيارة",
  "car rental": "تأجير سيارات",
  "daily rental": "إيجار يومي",
  "weekly rental": "إيجار أسبوعي",
  "monthly rental": "إيجار شهري",
  "insurance": "تأمين",
  "comprehensive insurance": "تأمين شامل",
  "third party insurance": "تأمين ضد الغير",
  "mileage": "المسافة المقطوعة / الكيلومترات",
  "fuel level": "مستوى الوقود",
  "damage inspection": "فحص الأضرار",

  // --- Colors, Sizes, Modifiers ---
  "small": "صغير",
  "medium": "وسط",
  "large": "كبير",
  "extra large": "كبير جداً",
  "xl": "XL",
  "xxl": "XXL",
  "black": "أسود",
  "white": "أبيض",
  "red": "أحمر",
  "blue": "أزرق",
  "green": "أخضر",
  "yellow": "أصفر",
  "orange_color": "برتقالي",
  "purple": "بنفسجي",
  "violet": "بنفسجي",
  "pink": "وردي",
  "brown": "بني",
  "grey": "رمادي",
  "gray": "رمادي",
  "beige": "بيج",
  "navy blue": "كحلي",
  "navy": "كحلي",
  "sky blue": "سماوي",
  "olive": "زيتي",
  "gold": "ذهبي",
  "golden": "ذهبي",
  "silver": "فضي",
  "bronze": "برونزي",
  "transparent": "شفاف",
  "clear": "شفاف",
  "light": "فاتح",
  "dark": "داكن / غامق",
  "shiny": "لامع",
  "matte": "مطفي",
  "plain": "سادة",
  "patterned": "مشجر / منقوش",
  "striped": "مخطط",
  "hot": "حار / ساخن",
  "cold": "بارد",
  "iced": "مثلج",
  "warm": "دافئ",
  "spicy": "حار",
  "normal": "عادي",
  "regular": "عادي",
  "extra": "إضافي",
  "double": "مزدوج / دبل",
  "triple": "ثلاثي",
  "fresh": "طازج",
  "frozen": "مجمد",
  "dried": "مجفف",
  "canned": "معلب",
  "organic": "عضوي",
  "sugar free": "خالي من السكر",
  "gluten free": "خالي من الجلوتين",
  "fat free": "خالي من الدسم",
  "diet": "دايت",
  "original": "أصلي",
  "standard": "قياسي",
  "premium": "فاخر / بريميوم",
  "deluxe": "ديلوكس",
  "classic": "كلاسيك",
  "modern": "حديث",
  "custom": "مخصص",
  "urgent": "مستعجل",
  "fast": "سريع",
  "vip": "VIP",
  "new": "جديد",
  "used": "مستعمل",
  "refurbished": "مجدد",

  // --- Saudi Cities & Landmarks ---
  "riyadh": "الرياض",
  "jeddah": "جدة",
  "mecca": "مكة المكرمة",
  "makkah": "مكة المكرمة",
  "medina": "المدينة المنورة",
  "madinah": "المدينة المنورة",
  "dammam": "الدمام",
  "khobar": "الخبر",
  "dhahran": "الظهران",
  "al ahsa": "الأحساء",
  "hofuf": "الهفوف",
  "jubail": "الجبيل",
  "qassim": "القصيم",
  "buraidah": "بريدة",
  "onaizah": "عنيزة",
  "taif": "الطائف",
  "tabuk": "تبوك",
  "abha": "أبها",
  "khamis mushait": "خميس مشيط",
  "jazan": "جازان",
  "najran": "نجران",
  "hail": "حائل",
  "yanbu": "ينبع",
  "arar": "عرعر",
  "sakaka": "سكاكا",
  "al jouf": "الجوف",

  // --- Famous Brands & Common Transliterations ---
  "almarai": "المراعي",
  "nadec": "نادك",
  "alsafi": "الصافي",
  "saudia": "السعودية",
  "nada": "ندى",
  "kdd": "كي دي دي",
  "pepsi": "بيبسي",
  "coca-cola": "كوكاكولا",
  "coca cola": "كوكاكولا",
  "sprite": "سبرايت",
  "7up": "سفن أب",
  "seven up": "سفن أب",
  "mirinda": "ميريندا",
  "fanta": "فانتا",
  "kinza": "كينزا",
  "mountain dew": "ماونتن ديو",
  "red bull": "ريد بول",
  "code red": "كود ريد",
  "bison": "بايسن",
  "aquafina": "أكوافينا",
  "arwa": "أروى",
  "nova": "نوفا",
  "berain": "بيرين",
  "tania": "تانيا",
  "hana": "هنا",
  "mozn": "مزن",
  "safia": "صفيا",
  "nestle": "نستله",
  "nutella": "نوتيلا",
  "kinder": "كيندر",
  "kitkat": "كيت كات",
  "galaxy": "جالكسي",
  "snickers": "سنيكرز",
  "twix": "تويكس",
  "bounty": "باونتي",
  "mars": "مارس",
  "m&m": "إم آند إمز",
  "cadbury": "كادبوري",
  "oreo": "أوريو",
  "lays": "ليز",
  "doritos": "دوريتوس",
  "cheetos": "شيتوس",
  "pringles": "برينجلز",
  "sunbites": "صن بايتس",
  "tasali": "تسالي",
  "indomie": "إندومي",
  "maggi": "ماجي",
  "knorr": "كنور",
  "lipton": "ليبتون",
  "nescafe": "نسكافيه",
  "tide": "تايد",
  "ariel": "أريال",
  "omo": "أومو",
  "fairy": "فيري",
  "pril": "بريل",
  "clorox": "كلوركس",
  "dettol": "دتول",
  "lux": "لوكس",
  "dove": "دوف",
  "head & shoulders": "هيد آند شولدرز",
  "pantene": "بانتين",
  "sunsilk": "صانسيلك",
  "colgate": "كولجيت",
  "signal": "سيجنال",
  "sensodyne": "سنسوداين",
  "nivea": "نيفيا",
  "vaseline": "فازلين",
  "pampers": "بامبرز",
  "huggies": "هاجيز",
  "fine": "فاين",
  "kleenex": "كلينكس",
  "samsung": "سامسونج",
  "apple": "أبل",
  "iphone": "آيفون",
  "ipad": "آيباد",
  "macbook": "ماك بوك",
  "airpods": "إيربودز",
  "huawei": "هواوي",
  "xiaomi": "شاومي",
  "sony": "سوني",
  "playstation": "بلايستيشن",
  "lenovo": "لينوفو",
  "dell": "ديل",
  "hp": "إتش بي",
  "asus": "أسوس",
  "acer": "إيسر",
  "canon": "كانون",
  "nikon": "نايكون",
  "lg": "إل جي",
  "panasonic": "باناسونيك",
  "philips": "فيليبس",
  "anker": "أنكر",
  "toyota": "تويوتا",
  "hyundai": "هيونداي",
  "kia": "كيا",
  "nissan": "نيسان",
  "ford": "فورد",
  "chevrolet": "شيفروليه",
  "gmc": "جي إم سي",
  "honda": "هوندا",
  "mazda": "مازدا",
  "mercedes": "مرسيدس",
  "bmw": "بي إم دبليو",
  "audi": "أودي",
  "lexus": "لكزس",
  "land cruiser": "لاند كروزر",
  "camry": "كامري",
  "corolla": "كورولا",
  "hilux": "هايلكس",
  "elantra": "إلنترا",
  "sonata": "سوناتا",
  "accent": "أكسنت",
  "tucson": "توسان",
  "santa fe": "سنتافي",
  "optima": "أوبتيما",
  "k5": "K5",
  "cerato": "سيراتو",
  "sportage": "سبورتاج",
  "patrol": "باترول",
  "sunny": "صني",
  "altima": "ألتيما",
  "stc": "إس تي سي",
  "mobily": "موبايلي",
  "zain": "زين",
  "virgin mobile": "فيرجن موبايل",
  "red bull mobile": "ريد بول موبايل",
  "salam": "سلام",
  "aramco": "أرامكو",
  "sabic": "سابك",
  "al rajhi": "الراجحي",
  "snb": "البنك الأهلي السعودي",
  "alinma": "الإنماء",
  "riyad bank": "بنك الرياض",
  "jarir": "جرير",
  "extra": "إكسترا",
  "panda": "بنده",
  "othaim": "العثيم",
  "luluh": "لولو",
  "danube": "الدانوب",
  "tamimi": "التميمي",
  "carrefour": "كارفور",
  "al baik": "البيك",
  "albaik": "البيك",
  "kudu": "كودو",
  "herfy": "هرفي",
  "barns": "بارنز",
  "dunkin": "دانكن",
  "starbucks": "ستاربكس",
  "half million": "هاف مليون",
  "dr cafe": "د. كيف"
};

// ── 2. REVERSE LOOKUP MAP (Arabic -> English) ────────────────────────────────
export const REVERSE_DICTIONARY = {};
Object.entries(DICTIONARY).forEach(([enKey, arVal]) => {
  const normAr = arVal.trim();
  // Primary exact match
  if (!REVERSE_DICTIONARY[normAr]) {
    REVERSE_DICTIONARY[normAr] = enKey;
  }
  // Also index slash variants if present e.g. "حبة / قطعة" -> "piece"
  if (normAr.includes('/')) {
    normAr.split('/').forEach(part => {
      const p = part.trim();
      if (p && !REVERSE_DICTIONARY[p]) {
        REVERSE_DICTIONARY[p] = enKey;
      }
    });
  }
});

// Common Arabic proper names dictionary
const AR_NAMES = {
  "محمد": "Mohammed",
  "احمد": "Ahmed",
  "أحمد": "Ahmed",
  "علي": "Ali",
  "حسن": "Hassan",
  "حسين": "Hussein",
  "خالد": "Khalid",
  "عبدالله": "Abdullah",
  "عبد الله": "Abdullah",
  "عبدالرحمن": "Abdulrahman",
  "عبد الرحمن": "Abdulrahman",
  "عبدالعزيز": "Abdulaziz",
  "عبد العزيز": "Abdulaziz",
  "سعود": "Saud",
  "سلطان": "Sultan",
  "فهد": "Fahad",
  "فيصل": "Faisal",
  "سلمان": "Salman",
  "تركي": "Turki",
  "بندر": "Bandar",
  "مشعل": "Meshal",
  "ناصر": "Nasser",
  "منصور": "Mansour",
  "سعد": "Saad",
  "سعيد": "Saeed",
  "عمر": "Omar",
  "عثمان": "Othman",
  "إبراهيم": "Ibrahim",
  "ابراهيم": "Ibrahim",
  "يوسف": "Youssef",
  "ياسر": "Yasser",
  "طارق": "Tariq",
  "ماجد": "Majed",
  "وليد": "Waleed",
  "صالح": "Saleh",
  "فاطمة": "Fatima",
  "مريم": "Maryam",
  "نورة": "Noura",
  "نوره": "Noura",
  "سارة": "Sara",
  "ساره": "Sara",
  "هند": "Hind",
  "ريم": "Reem",
  "منى": "Mona",
  "هدى": "Huda",
  "لولوة": "Lulwa",
  "دانة": "Dana",
  "دانه": "Dana",
  "العنود": "Alanoud",
  "شهد": "Shahad",
  "أمل": "Amal",
  "امل": "Amal",
  "منى": "Mona",
  "مها": "Maha",
  "عبير": "Abeer",
  "حنان": "Hanan",
  "خلود": "Kholoud",
  "روان": "Rawan"
};

// English proper names -> canonical Arabic spelling. Built from the reverse of
// AR_NAMES plus common alternate English transliterations, so everyday names
// (e.g. "Hassan") translate to their correct, natural Arabic spelling instead
// of being run through the generic letter-by-letter phonetic engine below.
const EN_NAMES = {};
Object.entries(AR_NAMES).forEach(([ar, en]) => {
  const key = en.toLowerCase();
  if (!EN_NAMES[key]) EN_NAMES[key] = ar;
});
Object.assign(EN_NAMES, {
  "muhammad": "محمد",
  "mohammad": "محمد",
  "mohamed": "محمد",
  "ahmad": "أحمد",
  "hasan": "حسن",
  "hussain": "حسين",
  "husain": "حسين",
  "khaled": "خالد",
  "abdallah": "عبدالله",
  "abdulla": "عبدالله",
  "abdurrahman": "عبدالرحمن",
  "fahd": "فهد",
  "faysal": "فيصل",
  "nasir": "ناصر",
  "mansur": "منصور",
  "said": "سعيد",
  "umar": "عمر",
  "uthman": "عثمان",
  "yousef": "يوسف",
  "yusuf": "يوسف",
  "yasir": "ياسر",
  "tarek": "طارق",
  "majid": "ماجد",
  "walid": "وليد",
  "salih": "صالح",
  "fatimah": "فاطمة",
  "mariam": "مريم",
  "miriam": "مريم",
  "nora": "نورة",
  "norah": "نورة",
  "sarah": "سارة",
  "rim": "ريم",
  "muna": "منى",
  "abir": "عبير",
  "kholoud": "خلود",
  "khulood": "خلود",
  "mishal": "مشعل",
  "abdulkarim": "عبدالكريم",
  "abdulmajeed": "عبدالمجيد",
  "abdulmajid": "عبدالمجيد",
  "rashid": "راشد",
  "rashed": "راشد",
  "hamad": "حمد",
  "hamad ": "حمد",
  "jaber": "جابر",
  "jabir": "جابر",
  "talal": "طلال",
  "badr": "بدر",
  "nawaf": "نواف",
  "fawaz": "فواز",
  "sami": "سامي",
  "ziad": "زياد",
  "amjad": "أمجد",
  "anas": "أنس",
  "karim": "كريم",
  "kareem": "كريم",
  "yazan": "يزن",
  "adel": "عادل",
  "emad": "عماد",
  "imad": "عماد",
  "bassam": "بسام",
  "rami": "رامي",
  "nabil": "نبيل",
  "hisham": "هشام",
  "bilal": "بلال",
  "hamza": "حمزة",
  "zaid": "زيد",
  "zayd": "زيد",
  "malik": "مالك",
  "aziz": "عزيز",
  "rakan": "راكان",
  "layla": "ليلى",
  "laila": "ليلى",
  "rania": "رانيا",
  "lama": "لمى",
  "ghada": "غادة",
  "latifa": "لطيفة",
  "basma": "بسمة",
  "munira": "منيرة",
  "areej": "أريج",
  "alia": "عالية",
  "aliya": "عالية",
  "nada": "ندى",
  "rahaf": "رهف",
  "joud": "جود",
  "elaf": "إيلاف",
  "retaj": "رتاج",
  "renad": "ريناد",
  "danah": "دانة",
  "asma": "أسماء",
  "asmaa": "أسماء",
  "raghad": "رغد",
  "wafa": "وفاء",
  "wafaa": "وفاء"
});

// ── 3. SMART PHONETIC TRANSLITERATION ENGINE ─────────────────────────────────
// High-fidelity English-to-Arabic phonetic rules
const PHONETIC_EN_TO_AR = [
  // Multi-character digraphs first
  [/sh/gi, 'ش'],
  [/ch/gi, 'تش'],
  [/th/gi, 'ث'],
  [/kh/gi, 'خ'],
  [/gh/gi, 'غ'],
  [/ph/gi, 'ف'],
  [/dh/gi, 'ض'],
  [/zh/gi, 'ز'],
  [/oo/gi, 'و'],
  [/ee/gi, 'ي'],
  [/ea/gi, 'ي'],
  [/ou/gi, 'و'],
  [/ai/gi, 'اي'],
  [/ay/gi, 'اي'],
  [/tion\b/gi, 'شن'],
  [/sion\b/gi, 'شن'],
  
  // Single consonants & vowels
  [/b/gi, 'ب'],
  [/c([eiy])/gi, 'س$1'],
  [/c/gi, 'ك'],
  [/d/gi, 'د'],
  [/f/gi, 'ف'],
  [/g/gi, 'ج'],
  [/h/gi, 'ه'],
  [/j/gi, 'ج'],
  [/k/gi, 'ك'],
  [/l/gi, 'ل'],
  [/m/gi, 'م'],
  [/n/gi, 'ن'],
  [/p/gi, 'ب'],
  [/q/gi, 'ق'],
  [/r/gi, 'ر'],
  [/s/gi, 'س'],
  [/t/gi, 'ت'],
  [/v/gi, 'ف'],
  [/w/gi, 'و'],
  [/x/gi, 'كس'],
  [/y/gi, 'ي'],
  [/z/gi, 'ز'],
  [/a/gi, 'ا'],
  [/e/gi, 'ي'],
  [/i/gi, 'ي'],
  [/o/gi, 'و'],
  [/u/gi, 'و']
];

export function transliterateEnToAr(word) {
  if (!word) return '';
  const lower = word.toLowerCase().trim();
  if (DICTIONARY[lower]) return DICTIONARY[lower];
  if (EN_NAMES[lower]) return EN_NAMES[lower];
  
  let res = lower;
  for (const [pattern, rep] of PHONETIC_EN_TO_AR) {
    res = res.replace(pattern, rep);
  }
  // Clean double Arabic vowels
  res = res.replace(/اا+/g, 'ا').replace(/يي+/g, 'ي').replace(/وو+/g, 'و');
  return res;
}

// Check if string contains Arabic characters
export const isArabicText = (text = '') => /[\u0600-\u06FF]/.test(String(text || ''));

// Normalize text for dictionary lookup
const normalizeText = (text = '') => {
  return String(text || '')
    .trim()
    .toLowerCase()
    .replace(/[,\-_.]+/g, ' ')
    .replace(/\s+/g, ' ');
};

// ── 4. UNIT / MEASUREMENT EXTRACTION ──────────────────────────────────────────
const UNIT_PATTERNS = [
  { regex: /(\d+(?:\.\d+)?)\s*(?:kg|kilo|kilogram|kilograms)\b/i, ar: (n) => `${n} كجم`, en: (n) => `${n} kg` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:g|gm|gram|grams)\b/i, ar: (n) => `${n} جم`, en: (n) => `${n} g` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:l|ltr|liter|liters|litre|litres)\b/i, ar: (n) => `${n} لتر`, en: (n) => `${n} L` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:ml|milliliter|milliliters)\b/i, ar: (n) => `${n} مل`, en: (n) => `${n} ml` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:m|meter|meters|metre|metres)\b/i, ar: (n) => `${n} متر`, en: (n) => `${n} m` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:cm|centimeter|centimeters)\b/i, ar: (n) => `${n} سم`, en: (n) => `${n} cm` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:mm|millimeter|millimeters)\b/i, ar: (n) => `${n} ملم`, en: (n) => `${n} mm` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:pcs|pc|piece|pieces)\b/i, ar: (n) => `${n} حبة`, en: (n) => `${n} pcs` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:pack|packs|packet|packets)\b/i, ar: (n) => `${n} باكت`, en: (n) => `${n} pack` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:box|boxes)\b/i, ar: (n) => `${n} كرتون`, en: (n) => `${n} box` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:can|cans)\b/i, ar: (n) => `${n} علبة`, en: (n) => `${n} can` },
  { regex: /(\d+(?:\.\d+)?)\s*(?:bottle|bottles)\b/i, ar: (n) => `${n} قارورة`, en: (n) => `${n} bottle` },
];

// ── 5. MAIN TRANSLATION FUNCTIONS ────────────────────────────────────────────

/**
 * Translates English text to Arabic using built-in dictionary, grammar rules & transliteration
 * @param {string} text - English input string
 * @returns {string} - Arabic translation
 */
export function translateEnglishToArabic(text) {
  if (!text || typeof text !== 'string') return '';
  const trimmed = text.trim();
  if (!trimmed) return '';
  
  // If already Arabic, return as-is
  if (isArabicText(trimmed)) return trimmed;

  const normalized = normalizeText(trimmed);

  // 1. Direct dictionary match
  if (DICTIONARY[normalized]) {
    return cleanTranslation(DICTIONARY[normalized]);
  }

  // 1b. Known proper name match (people's names) — takes priority over the
  // generic phonetic engine, which cannot reliably guess correct Arabic
  // spelling for names (e.g. double letters, silent sounds).
  if (EN_NAMES[normalized]) {
    return EN_NAMES[normalized];
  }

  // 2. Extract unit/measurement suffix or prefix if present e.g. "Almarai Milk 1L" -> "حليب المراعي 1 لتر"
  let extractedUnitAr = '';
  let cleanedBaseText = trimmed;
  for (const unit of UNIT_PATTERNS) {
    const match = cleanedBaseText.match(unit.regex);
    if (match) {
      extractedUnitAr = unit.ar(match[1]);
      cleanedBaseText = cleanedBaseText.replace(match[0], '').trim();
      break;
    }
  }

  const baseNorm = normalizeText(cleanedBaseText);
  if (baseNorm && DICTIONARY[baseNorm]) {
    const baseAr = cleanTranslation(DICTIONARY[baseNorm]);
    return extractedUnitAr ? `${baseAr} ${extractedUnitAr}` : baseAr;
  }

  // 3. Tokenize words and compound phrases
  const words = cleanedBaseText.split(/\s+/).filter(Boolean);
  if (words.length === 0) return extractedUnitAr || trimmed;

  // Try sub-phrase chunks (n-grams from longest to 1)
  const translatedTokens = [];
  let i = 0;
  while (i < words.length) {
    let matched = false;
    // Check 3-word phrase
    if (i + 2 < words.length) {
      const phrase3 = `${words[i]} ${words[i+1]} ${words[i+2]}`.toLowerCase();
      if (DICTIONARY[phrase3]) {
        translatedTokens.push(cleanTranslation(DICTIONARY[phrase3]));
        i += 3;
        matched = true;
        continue;
      }
    }
    // Check 2-word phrase
    if (i + 1 < words.length) {
      const phrase2 = `${words[i]} ${words[i+1]}`.toLowerCase();
      if (DICTIONARY[phrase2]) {
        translatedTokens.push(cleanTranslation(DICTIONARY[phrase2]));
        i += 2;
        matched = true;
        continue;
      }
    }
    // Single word
    const singleWord = words[i].toLowerCase();
    // Numbers or symbols stay as is
    if (/^[\d+/*\-#.]+$/.test(singleWord)) {
      translatedTokens.push(words[i]);
    } else if (DICTIONARY[singleWord]) {
      translatedTokens.push(cleanTranslation(DICTIONARY[singleWord]));
    } else if (EN_NAMES[singleWord]) {
      translatedTokens.push(EN_NAMES[singleWord]);
    } else {
      // Phonetic transliteration for unknown proper names / brand words
      translatedTokens.push(transliterateEnToAr(words[i]));
    }
    i++;
  }

  let finalArabic = translatedTokens.join(' ').trim();
  if (extractedUnitAr) {
    finalArabic = `${finalArabic} ${extractedUnitAr}`;
  }

  return finalArabic || trimmed;
}

/**
 * Translates Arabic text to English using built-in dictionary & rules
 * @param {string} text - Arabic input string
 * @returns {string} - English translation
 */
export function translateArabicToEnglish(text) {
  if (!text || typeof text !== 'string') return '';
  const trimmed = text.trim();
  if (!trimmed) return '';
  
  // If already pure Latin/English, return as-is
  if (!isArabicText(trimmed)) return trimmed;

  const normalized = normalizeText(trimmed);

  // 1. Direct reverse dictionary match
  if (REVERSE_DICTIONARY[normalized]) {
    return capitalizeWords(REVERSE_DICTIONARY[normalized]);
  }
  if (AR_NAMES[normalized]) {
    return AR_NAMES[normalized];
  }

  // 2. Extract unit/measurement suffix if present e.g. "حليب المراعي 1 لتر"
  let extractedUnitEn = '';
  let cleanedBaseText = trimmed;
  for (const unit of UNIT_PATTERNS) {
    const match = cleanedBaseText.match(unit.regex);
    if (match) {
      extractedUnitEn = unit.en(match[1]);
      cleanedBaseText = cleanedBaseText.replace(match[0], '').trim();
      break;
    }
  }

  // Check Arabic name / dictionary on cleaned base
  const cleanNorm = normalizeText(cleanedBaseText);
  if (cleanNorm && REVERSE_DICTIONARY[cleanNorm]) {
    const baseEn = capitalizeWords(REVERSE_DICTIONARY[cleanNorm]);
    return extractedUnitEn ? `${baseEn} ${extractedUnitEn}` : baseEn;
  }
  if (cleanNorm && AR_NAMES[cleanNorm]) {
    const nameEn = AR_NAMES[cleanNorm];
    return extractedUnitEn ? `${nameEn} ${extractedUnitEn}` : nameEn;
  }

  // 3. Tokenize words
  const words = cleanedBaseText.split(/\s+/).filter(Boolean);
  const translatedTokens = [];

  for (const w of words) {
    const wNorm = w.trim();
    if (/^[\d+/*\-#.]+$/.test(wNorm)) {
      translatedTokens.push(wNorm);
    } else if (REVERSE_DICTIONARY[wNorm]) {
      translatedTokens.push(capitalizeWords(REVERSE_DICTIONARY[wNorm]));
    } else if (AR_NAMES[wNorm]) {
      translatedTokens.push(AR_NAMES[wNorm]);
    } else {
      // Keep as-is or capitalize
      translatedTokens.push(w);
    }
  }

  let finalEnglish = translatedTokens.join(' ').trim();
  if (extractedUnitEn) {
    finalEnglish = `${finalEnglish} ${extractedUnitEn}`;
  }

  return finalEnglish || trimmed;
}

/**
 * Universal auto-translator function (detects source language or accepts explicit direction)
 * @param {string} text - Text to translate
 * @param {string} [fromLang] - 'en', 'ar', 'English', 'Arabic' or auto
 * @param {string} [toLang] - 'en', 'ar', 'English', 'Arabic' or auto
 * @returns {string}
 */
export function autoTranslateText(text, fromLang, toLang) {
  if (!text || typeof text !== 'string') return '';
  const trimmed = text.trim();
  if (!trimmed) return '';

  const isAr = isArabicText(trimmed);
  const target = String(toLang || '').toLowerCase();
  
  if (target === 'ar' || target === 'arabic' || (!toLang && !isAr)) {
    return translateEnglishToArabic(trimmed);
  } else if (target === 'en' || target === 'english' || (!toLang && isAr)) {
    return translateArabicToEnglish(trimmed);
  }

  // If already matches target, return
  return isAr ? translateArabicToEnglish(trimmed) : translateEnglishToArabic(trimmed);
}

// Helpers
function cleanTranslation(val) {
  if (!val) return '';
  // If dictionary has slash variants e.g. "حبة / قطعة", pick first clean variant
  if (val.includes(' / ')) {
    return val.split(' / ')[0].trim();
  }
  return val.trim();
}

function capitalizeWords(str) {
  if (!str) return '';
  return str.replace(/\b\w/g, char => char.toUpperCase());
}

export default {
  translateEnglishToArabic,
  translateArabicToEnglish,
  autoTranslateText,
  isArabicText,
  DICTIONARY,
  REVERSE_DICTIONARY
};
