// Country → default currency, timezone, tax rate, and compliance authority.
// Aligned with GCC multi-country architecture.

export const COUNTRY_OPTIONS = [
  {
    code: 'SA',
    nameEn: 'Saudi Arabia',
    nameAr: 'المملكة العربية السعودية',
    currency: 'SAR',
    symbol: '﷼',
    timezone: 'Asia/Riyadh',
    vatRate: 15,
    authority: 'ZATCA',
    taxLabelEn: 'VAT (15%)',
    taxLabelAr: 'ضريبة القيمة المضافة (15%)',
    idLabelEn: 'VAT Number (15 digits)',
    idLabelAr: 'الرقم الضريبي (15 خانة)',
    arabic: true,
  },
  {
    code: 'AE',
    nameEn: 'United Arab Emirates',
    nameAr: 'الإمارات العربية المتحدة',
    currency: 'AED',
    symbol: 'د.إ',
    timezone: 'Asia/Dubai',
    vatRate: 5,
    authority: 'FTA',
    taxLabelEn: 'VAT (5%)',
    taxLabelAr: 'ضريبة القيمة المضافة (5%)',
    idLabelEn: 'TRN (15 digits)',
    idLabelAr: 'الرقم الضريبي TRN (15 خانة)',
    arabic: true,
  },
  {
    code: 'QA',
    nameEn: 'Qatar',
    nameAr: 'دولة قطر',
    currency: 'QAR',
    symbol: 'ر.ق',
    timezone: 'Asia/Qatar',
    vatRate: 0,
    authority: 'GTA',
    taxLabelEn: 'Dhareeba Tax',
    taxLabelAr: 'ضريبة قطر / ضريبة الدخل',
    idLabelEn: 'TIN (Tax ID)',
    idLabelAr: 'رقم التعريف الضريبي TIN',
    arabic: true,
  },
  {
    code: 'KW',
    nameEn: 'Kuwait',
    nameAr: 'دولة الكويت',
    currency: 'KWD',
    symbol: 'د.ك',
    timezone: 'Asia/Kuwait',
    vatRate: 0,
    authority: 'MOF',
    taxLabelEn: 'Commercial & Retention Tax',
    taxLabelAr: 'الضريبة التجارية وحجز الضريبة',
    idLabelEn: 'Civil ID / Tax Card',
    idLabelAr: 'الرقم المدني / البطاقة الضريبية',
    arabic: true,
  },
  {
    code: 'BH',
    nameEn: 'Bahrain',
    nameAr: 'مملكة البحرين',
    currency: 'BHD',
    symbol: '.د.ب',
    timezone: 'Asia/Bahrain',
    vatRate: 10,
    authority: 'NBR',
    taxLabelEn: 'VAT (10%)',
    taxLabelAr: 'ضريبة القيمة المضافة (10%)',
    idLabelEn: 'VAT Account No (15 digits)',
    idLabelAr: 'رقم الحساب الضريبي (15 خانة)',
    arabic: true,
  },
  {
    code: 'OM',
    nameEn: 'Oman',
    nameAr: 'سلطنة عُمان',
    currency: 'OMR',
    symbol: 'ر.ع.',
    timezone: 'Asia/Muscat',
    vatRate: 5,
    authority: 'OTA',
    taxLabelEn: 'VAT (5%)',
    taxLabelAr: 'ضريبة القيمة المضافة (5%)',
    idLabelEn: 'TIN / VAT Number',
    idLabelAr: 'الرقم التعريفي الضريبي TIN',
    arabic: true,
  },
  {
    code: 'BD',
    nameEn: 'Bangladesh',
    nameAr: 'بنغلاديش',
    currency: 'BDT',
    symbol: '৳',
    timezone: 'Asia/Dhaka',
    vatRate: 15,
    authority: 'NBR',
    taxLabelEn: 'Mushak VAT (15%)',
    taxLabelAr: 'ضريبة موشاك (15%)',
    idLabelEn: 'BIN (Business ID Number)',
    idLabelAr: 'رقم التعريف التجاري BIN',
    arabic: false,
  },
  {
    code: 'PK',
    nameEn: 'Pakistan',
    nameAr: 'باكستان',
    currency: 'PKR',
    symbol: '₨',
    timezone: 'Asia/Karachi',
    vatRate: 18,
    authority: 'FBR',
    taxLabelEn: 'Sales Tax / GST (18%)',
    taxLabelAr: 'ضريبة المبيعات GST (18%)',
    idLabelEn: 'NTN / STRN',
    idLabelAr: 'الرقم الضريبي NTN / STRN',
    arabic: false,
  },
  {
    code: 'EG',
    nameEn: 'Egypt',
    nameAr: 'جمهورية مصر العربية',
    currency: 'EGP',
    symbol: 'ج.م',
    timezone: 'Africa/Cairo',
    vatRate: 14,
    authority: 'ETA',
    taxLabelEn: 'VAT (14%)',
    taxLabelAr: 'ضريبة القيمة المضافة (14%)',
    idLabelEn: 'Tax Registration No',
    idLabelAr: 'رقم التسجيل الضريبي',
    arabic: true,
  },
  {
    code: 'JO',
    nameEn: 'Jordan',
    nameAr: 'المملكة الأردنية الهاشمية',
    currency: 'JOD',
    symbol: 'د.ا',
    timezone: 'Asia/Amman',
    vatRate: 16,
    authority: 'ISTD',
    taxLabelEn: 'Sales Tax (16%)',
    taxLabelAr: 'ضريبة المبيعات العامة (16%)',
    idLabelEn: 'National Tax Number',
    idLabelAr: 'الرقم الضريبي الوطني',
    arabic: true,
  },
  {
    code: 'IN',
    nameEn: 'India',
    nameAr: 'الهند',
    currency: 'INR',
    symbol: '₹',
    timezone: 'Asia/Kolkata',
    vatRate: 18,
    authority: 'GSTN',
    taxLabelEn: 'GST (18%)',
    taxLabelAr: 'ضريبة السلع والخدمات GST',
    idLabelEn: 'GSTIN (15 digits)',
    idLabelAr: 'رقم GSTIN',
    arabic: false,
  },
  {
    code: 'US',
    nameEn: 'United States',
    nameAr: 'الولايات المتحدة الأمريكية',
    currency: 'USD',
    symbol: '$',
    timezone: 'America/New_York',
    vatRate: 0,
    authority: 'IRS',
    taxLabelEn: 'Sales Tax',
    taxLabelAr: 'ضريبة المبيعات',
    idLabelEn: 'EIN / SSN',
    idLabelAr: 'رقم تعريف صاحب العمل EIN',
    arabic: false,
  },
  {
    code: 'GB',
    nameEn: 'United Kingdom',
    nameAr: 'المملكة المتحدة',
    currency: 'GBP',
    symbol: '£',
    timezone: 'Europe/London',
    vatRate: 20,
    authority: 'HMRC',
    taxLabelEn: 'VAT (20%)',
    taxLabelAr: 'ضريبة القيمة المضافة VAT (20%)',
    idLabelEn: 'GB VAT Number (9 digits)',
    idLabelAr: 'رقم ضريبة القيمة المضافة البريطاني',
    arabic: false,
  },
  {
    code: 'TR',
    nameEn: 'Turkey',
    nameAr: 'تركيا',
    currency: 'TRY',
    symbol: '₺',
    timezone: 'Europe/Istanbul',
    vatRate: 20,
    authority: 'GIB',
    taxLabelEn: 'KDV (20%)',
    taxLabelAr: 'ضريبة KDV (20%)',
    idLabelEn: 'VKN (Tax ID)',
    idLabelAr: 'رقم الهوية الضريبية VKN',
    arabic: false,
  },
  {
    code: 'MY',
    nameEn: 'Malaysia',
    nameAr: 'ماليزيا',
    currency: 'MYR',
    symbol: 'RM',
    timezone: 'Asia/Kuala_Lumpur',
    vatRate: 6,
    authority: 'LHDN',
    taxLabelEn: 'SST (6%)',
    taxLabelAr: 'ضريبة المبيعات والخدمات SST',
    idLabelEn: 'SST Number',
    idLabelAr: 'رقم التسجيل SST',
    arabic: false,
  },
  {
    code: 'SG',
    nameEn: 'Singapore',
    nameAr: 'سنغافورة',
    currency: 'SGD',
    symbol: 'S$',
    timezone: 'Asia/Singapore',
    vatRate: 9,
    authority: 'IRAS',
    taxLabelEn: 'GST (9%)',
    taxLabelAr: 'ضريبة السلع والخدمات GST (9%)',
    idLabelEn: 'UEN / GST Reg No',
    idLabelAr: 'رقم الكيان الموحد UEN',
    arabic: false,
  },
  {
    code: 'OTHER',
    nameEn: 'Other (International)',
    nameAr: 'دولة أخرى (دولي)',
    currency: 'USD',
    symbol: '$',
    timezone: 'UTC',
    vatRate: 0,
    authority: 'TAX',
    taxLabelEn: 'Tax / VAT',
    taxLabelAr: 'الضريبة',
    idLabelEn: 'Tax Identification Number',
    idLabelAr: 'الرقم الضريبي',
    arabic: false,
  },
];

export const getCountryOption = (code) =>
  COUNTRY_OPTIONS.find((c) => c.code === String(code || '').toUpperCase()) || null;

export const currencyForCountry = (code) => getCountryOption(code)?.currency || 'USD';

export const timezoneForCountry = (code) => getCountryOption(code)?.timezone || 'Asia/Riyadh';

export const vatRateForCountry = (code) => getCountryOption(code)?.vatRate ?? 15;

export const isArabicCountry = (code) => Boolean(getCountryOption(code)?.arabic);

export const countryForCurrency = (currency) => {
  const cur = String(currency || '').trim().toUpperCase();
  return COUNTRY_OPTIONS.find((c) => c.currency === cur) || null;
};
